steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/angular-vector-456406-i8/myapp:latest',
      '.'
    ]

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/angular-vector-456406-i8/myapp:latest'
    ]

  # Step 3: SSH into the VM and deploy the image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh vm-m \
          --zone=us-central1-c \
          --command="sudo docker pull gcr.io/angular-vector-456406-i8/myapp:latest && sudo docker stop myapp || true && sudo docker rm myapp || true && sudo docker run -d --name myapp -p 80:80 gcr.io/angular-vector-456406-i8/myapp:latest"

images:
  - 'gcr.io/angular-vector-456406-i8/myapp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
